"""empty message

Revision ID: 28b11fa2bd1e
Revises: 
Create Date: 2026-02-05 06:00:35.462772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28b11fa2bd1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musicparties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DRUMS', 'VOCALS', 'GUITAR', 'BASS', 'KEYS', 'STRINGS', '_RUSSIAN_NAMES', name='project_type_enum'), nullable=False),
    sa.Column('genre', sa.Enum('ROCK', 'POP', 'JAZZ', 'ELECTRONIC', 'HIPHOP', 'CLASSICAL', '_RUSSIAN_NAMES', name='genre_enum'), nullable=True),
    sa.Column('mood', sa.Enum('HAPPY', 'ENERGETIC', 'CALM', 'SAD', 'EPIC', '_RUSSIAN_NAMES', name='mood_enum'), nullable=True),
    sa.Column('tempo', sa.Enum('SLOW', 'MEDIUM', 'FAST', 'VERY_FAST', '_BPM_RANGES', '_RUSSIAN_NAMES', name='tempo_enum'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('musicparties')
    op.drop_table('projects')
    op.drop_table('accounts')
    # ### end Alembic commands ###
